print("(**%PROTOCAL01011010%**)")
print("[0][1][EXEC START][1][0]")
print("")
print("")
print("EMTECH EST 1984")
print("")
print("<|||||||||||||>")
print("_______________")
print("")
print("CALSIGN OS V3.4")
print("_____________________________________________")